### PR TITLE
JS article

### PR DESCRIPTION
**Pull request by mxio**
I've written my JS article on window.length

### CODE REVIEW

**Comment by mxio** [comment]
I added a javascript file which so far has the ability to add a message to the chat log

**Comment by mxio** [comment]
The current chat feature still has problems. chatInput is empty when I submit. However, if I refresh and submit again, the log shows the message. But this message is repeated even when a new one is written.

**Comment by mxio** [comment]
Chat log is working now but only if I use document.getElementById in the innerHTML, not the variable to store the input value.

I am adding interactive encyclopedia entries.

**Comment by cbracco** [comment]
@mxio Hey nice! I am about halfway through **Introduction to the DOM**, will have a look at this sometime over the weekend. Thanks for the great start! 💯

**Comment by cbracco** [comment]
Hey @mxio! I am sorry I haven’t had a chance to look at this yet. I am participating in the practice hackathon this weekend, and I am also still working on **Introduction to the DOM** (all I have left are the project assignments, I worked through all exercises and questions). I wanted to give you an update so we’re on the same page. I hope to finish up the chapter and begin working on the team assignment during next week/weekend.

**Comment by mxio** [comment]
That's fine. I was assigned the next chapter so I should be good to go while you finish up the projects. Thanks for updating me!

**Pull request merged**
