### PR TITLE
Added styling to chat app

### PR DESCRIPTION
**Pull request by mxio**
I've done the remaining CSS styling. The only problem I ran into is the reverse chat record's arrow (right side). When resizing the window, the arrow doesn't stay right by the chat box. However, this is not the case for the regular chat record (left side). Both are set to absolute positioning so I'm not sure why it works for the left side's arrows but not the right side's. 

If you could look into it and let me know what's wrong, that would be great.

### CODE REVIEW

**Comment by cbracco** [comment]
@mxio this is great! i refactored your additions a bit to use the CSS variables, and changed some of the classes to give each chat bubble a "theme" class instead of styling sibling elements like we were doing previously. its feeling pretty good...

**Comment by mxio** [comment]
I took a look and that's much more clean. Thanks! By the way, the say something bubble arrow is set to 

--chat-textarea-arrow-before-top: 20px;

I think it should be set to 19.5px because at 20px, I can see there is a bit more space at the bottom of the arrow. 19.5px will make the top and bottom spaced evenly.

**Comment by cbracco** [comment]
Cool! What browser are you viewing from? I am using Chrome latest, I’m not sure I am seeing the issue you describe. Can you snap a screenshot of what you are seeing?

**Comment by mxio** [comment]
I'm using Firefox. Didn't realize it would be a browser issue lol

**Comment by cbracco** [comment]
@mxio Hmm, I am not seeing the issue in Firefox (latest version) either. Can you take a screenshot of what you are seeing, and post it here?

**Comment by mxio** [comment]
saysomething
It is slightly off center here, although it is not as noticeable because the image is smaller.

**Comment by mxio** [comment]
saysomething2

This is how it should look like at 19.5px

**Comment by cbracco** [comment]
@mxio ahh i see what you mean. yeah, that is a browser rounding error! firefox and chrome round values  a bit differently in certain situations. I can actually add styles so that the 19.5px will only apply to firefox browsers, will push up a fix for this in a few. nice catch!

**Comment by cbracco** [comment]
@mxio haha, its funny, when I change the value to `19.5px`, I am seeing it misaligned. Looking in Chrome latest and Firefox latest. Are you using an older version of Firefox, by any chance?

**Comment by mxio** [comment]
Hmm. My firefox is version 47.0. If its appearing fine on your end, we can just leave it be.

**Comment by cbracco** [comment]
Okay, if it becomes a big issue we can always revisit it. Thanks for being flexible!

**Pull request merged**
